### ISSUE TITLE
NPE crash on server

### ISSUE THREAD

**Issue by yaroslav4167** [codetaylor/pyrotech#176]
#### Crash Log

```
java.lang.NullPointerException: Exception ticking world
        at com.codetaylor.mc.pyrotech.modules.tech.refractory.tile.TileActivePile.func_189515_b(TileActivePile.java:359)
        at com.codetaylor.mc.pyrotech.library.spi.tile.TileNetBase.func_189517_E_(TileNetBase.java:52)
        at net.minecraft.network.play.server.SPacketChunkData.<init>(SourceFile:52)
        at net.minecraft.server.management.PlayerChunkMapEntry.func_187272_b(PlayerChunkMapEntry.java:640)
        at net.minecraft.server.management.PlayerChunkMap.func_72693_b(SourceFile:165)
        at net.minecraft.world.WorldServer.func_72835_b(WorldServer.java:227)
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:756)
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:397)
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668)
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
        at java.lang.Thread.run(Thread.java:748)
```

#### Affected Versions

* Minecraft: 1.12.2
* Forge: 14.23.5.2838
* CraftTweaker: 4.1.19
* Dropt: 1.12.2-1.15.1
* Pyrotech: 1.12.2-1.3.10
* Athenaeum: 1.12.2-1.17.3
* SpongeForge: 1.12.2-2838-7.1.7-RC3863

**Comment by codetaylor** [comment]
The given log indicates that the crash occurred because `TileActivePile` field `recipeKey` was null. The field is set immediately after creating the TE and is always serialized with the TE. The field should never be null under normal conditions and I can't find a case where it would be.

It's possible it has something to do with SpongeForge, I'm not familiar enough with it to say.

Can you provide steps to reliably reproduce this?

**Comment by yaroslav4167** [comment]
This error caused by player in server. I will try to find out from him how he caused this error.

**Comment by yaroslav4167** [comment]
I apparently found the source of the problem.
I just set the Log Pile on fire and the server crashed.
The Log Pile block itself was installed in the privatized territory of griefprevention plugin.

**Comment by codetaylor** [comment]
Were you able to fix the problem then?

**Comment by yaroslav4167** [comment]
I cannot remove the griefprevention plugin.
There is no solution to the problem yet.

**Comment by yaroslav4167** [comment]
Just in case, I recorded a [Video recreation of a bug](https://youtu.be/gPZ_i232MIE)

**Comment by codetaylor** [comment]
What is the significance of the yellow blocks turning red?

**Comment by yaroslav4167** [comment]
This is just a visualization of the borders of the privatization zone.
It can be seen by clicking on the right mouse button. It automatically disappears with time.

**Comment by codetaylor** [comment]
I understand, thanks.

**Comment by codetaylor** [comment]
Do you still get the crash when the pit burn completes normally?

**Comment by yaroslav4167** [comment]
I don’t know how to fix it.
Is something updated?

**Comment by codetaylor** [comment]
No. In your video you show that the crash occurs when a Pit Burn ingredient is lit and left uncovered and burns up. What I'm asking is if you bury the ingredient and light it, following the normal Pit Burn steps, does the crash still happen?

**Comment by yaroslav4167** [comment]
Oh.. Sorry. My english is bad xD
I'll try to check now.

**Comment by yaroslav4167** [comment]
![mWX3vJB2A5](https://user-images.githubusercontent.com/18057310/64081032-aa728400-ccfb-11e9-852e-850ec60b300f.png)
If you are waiting for the end with the door closed, then everything is in order.
But, if the door is open at the time of the burning process, the server will crash.

**Comment by codetaylor** [comment]
Understood, thanks :)
