### ISSUE TITLE
Can't interact with mechanical hoppers in dedicated server

### ISSUE THREAD

**Issue by Kurtchekov** [codetaylor/pyrotech#21]
#### Issue Description

Once the mechanical hopper has been placed, it can't be removed nor it accepts cogs. Meanwhile, the dedicated server throws the following exception whenever interaction with the hopper is attempted:

```
java.util.concurrent.ExecutionException: java.lang.NoClassDefFoundError: com/codetaylor/mc/pyrotech/modules/tech/machine/tile/spi/TileCogWorkerBase$ClientRenderData
Caused by: java.lang.NoClassDefFoundError: com/codetaylor/mc/pyrotech/modules/tech/machine/tile/spi/TileCogWorkerBase$ClientRenderData
        at com.codetaylor.mc.pyrotech.modules.tech.machine.tile.spi.TileCogWorkerBase.<init>(TileCogWorkerBase.java:48) ~[TileCogWorkerBase.class:?]
        at com.codetaylor.mc.pyrotech.modules.tech.machine.tile.TileStoneHopper.<init>(TileStoneHopper.java:25) ~[TileStoneHopper.class:?]
        at com.codetaylor.mc.pyrotech.modules.tech.machine.block.BlockMechanicalHopper.createTileEntity(BlockMechanicalHopper.java:180) ~[BlockMechanicalHopper.class:?]
```

#### Affected Versions

* Minecraft: 1.12.2
* Forge: 14.23.5.2838
* Dropt: 1.14.0
* Pyrotech: 1.0.3
* Athenaeum: 1.17.1

**Comment by codetaylor** [comment]
Confirmed. Full trace:

```
java.util.concurrent.ExecutionException: java.lang.NoClassDefFoundError: com/codetaylor/mc/pyrotech/modules/tech/machine/tile/spi/TileCogWorkerBase$ClientRenderData
	at java.util.concurrent.FutureTask.report(FutureTask.java:122) ~[?:1.8.0_144]
	at java.util.concurrent.FutureTask.get(FutureTask.java:192) ~[?:1.8.0_144]
	at net.minecraft.util.Util.runTask(Util.java:54) [Util.class:?]
	at net.minecraft.server.MinecraftServer.updateTimeLightAndEntities(MinecraftServer.java:798) [MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.updateTimeLightAndEntities(DedicatedServer.java:415) [DedicatedServer.class:?]
	at net.minecraft.server.MinecraftServer.tick(MinecraftServer.java:743) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:592) [MinecraftServer.class:?]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_144]
Caused by: java.lang.NoClassDefFoundError: com/codetaylor/mc/pyrotech/modules/tech/machine/tile/spi/TileCogWorkerBase$ClientRenderData
	at com.codetaylor.mc.pyrotech.modules.tech.machine.tile.spi.TileCogWorkerBase.<init>(TileCogWorkerBase.java:48) ~[TileCogWorkerBase.class:?]
	at com.codetaylor.mc.pyrotech.modules.tech.machine.tile.TileStoneHopper.<init>(TileStoneHopper.java:25) ~[TileStoneHopper.class:?]
	at com.codetaylor.mc.pyrotech.modules.tech.machine.block.BlockMechanicalHopper.createTileEntity(BlockMechanicalHopper.java:180) ~[BlockMechanicalHopper.class:?]
	at net.minecraft.world.chunk.Chunk.createNewTileEntity(Chunk.java:839) ~[Chunk.class:?]
	at net.minecraft.world.chunk.Chunk.getTileEntity(Chunk.java:857) ~[Chunk.class:?]
	at net.minecraft.world.World.getTileEntity(World.java:2613) ~[World.class:?]
	at mcp.mobius.waila.network.MessageRequestTile$Handler.lambda$onMessage$0(MessageRequestTile.java:69) ~[MessageRequestTile$Handler.class:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_144]
	at java.util.concurrent.FutureTask.run$$$capture(FutureTask.java:266) ~[?:1.8.0_144]
	at java.util.concurrent.FutureTask.run(FutureTask.java) ~[?:1.8.0_144]
	at net.minecraft.util.Util.runTask(Util.java:53) ~[Util.class:?]
	... 5 more
```
