### ISSUE TITLE
Server Tick Loop Crash

### ISSUE THREAD

**Issue by SweetVirtue** [codetaylor/pyrotech#283]
I would be very grateful if you can find a solution!

The game crashed whilst exception in server tick loop
Error: com.google.common.util.concurrent.ExecutionError: java.lang.NoSuchMethodError: net.minecraftforge.fml.common.ObfuscationReflectionHelper.findField(Ljava/lang/Class;Ljava/lang/String;)Ljava/lang/reflect/Field;

detailed crash report:

---- Minecraft Crash Report ----
// You're mean.

Time: 3/13/20 11:01 PM
Description: Exception in server tick loop

com.google.common.util.concurrent.ExecutionError: java.lang.NoSuchMethodError: net.minecraftforge.fml.common.ObfuscationReflectionHelper.findField(Ljava/lang/Class;Ljava/lang/String;)Ljava/lang/reflect/Field;
	at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2215)
	at com.google.common.cache.LocalCache.get(LocalCache.java:4154)
	at com.google.common.cache.LocalCache.getOrLoad(LocalCache.java:4158)
	at com.google.common.cache.LocalCache$LocalLoadingCache.get(LocalCache.java:5147)
	at com.google.common.cache.LocalCache$LocalLoadingCache.getUnchecked(LocalCache.java:5153)
	at net.minecraft.world.storage.loot.LootTableManager.func_186521_a(LootTableManager.java:40)
	at net.minecraft.world.storage.loot.LootTableManager.func_186522_a(LootTableManager.java:49)
	at net.minecraft.world.storage.loot.LootTableManager.<init>(LootTableManager.java:35)
	at net.minecraft.world.WorldServer.func_175643_b(WorldServer.java:155)
	at net.minecraft.server.integrated.IntegratedServer.func_71247_a(IntegratedServer.java:122)
	at net.minecraft.server.integrated.IntegratedServer.func_71197_b(IntegratedServer.java:156)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:486)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.NoSuchMethodError: net.minecraftforge.fml.common.ObfuscationReflectionHelper.findField(Ljava/lang/Class;Ljava/lang/String;)Ljava/lang/reflect/Field;
	at com.codetaylor.mc.pyrotech.modules.core.event.LootTableLoadEventHandler.<clinit>(LootTableLoadEventHandler.java:44)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_24_LootTableLoadEventHandler_on_LootTableLoadEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
	at net.minecraftforge.event.ForgeEventFactory.loadLootTable(ForgeEventFactory.java:752)
	at net.minecraftforge.common.ForgeHooks.loadLootTable(ForgeHooks.java:1173)
	at net.minecraft.world.storage.loot.LootTableManager$Loader.func_186518_c(LootTableManager.java:156)
	at net.minecraft.world.storage.loot.LootTableManager$Loader.load(LootTableManager.java:72)
	at net.minecraft.world.storage.loot.LootTableManager$Loader.load(LootTableManager.java:53)
	at com.google.common.cache.LocalCache$LoadingValueReference.loadFuture(LocalCache.java:3716)
	at com.google.common.cache.LocalCache$Segment.loadSync(LocalCache.java:2424)
	at com.google.common.cache.LocalCache$Segment.lockedGetOrLoad(LocalCache.java:2298)
	at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2211)
	... 12 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 281417224 bytes (268 MB) / 671088640 bytes (640 MB) up to 2147483648 bytes (2048 MB)
	JVM Flags: 8 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.42 Powered by Forge 14.23.5.2768 7 mods loaded, 7 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State   | ID        | Version       | Source                        | Signature                                |
	|:------- |:--------- |:------------- |:----------------------------- |:---------------------------------------- |
	| UCHIJAA | minecraft | 1.12.2        | minecraft.jar                 | None                                     |
	| UCHIJAA | mcp       | 9.42          | minecraft.jar                 | None                                     |
	| UCHIJAA | FML       | 8.0.99.99     | forge-1.12.2-14.23.5.2768.jar | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCHIJAA | forge     | 14.23.5.2768  | forge-1.12.2-14.23.5.2768.jar | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCHIJAA | athenaeum | 1.12.2-1.17.4 | athenaeum-1.12.2-1.17.4.jar   | None                                     |
	| UCHIJAA | dropt     | 1.12.2-1.17.0 | dropt-1.12.2-1.17.0.jar       | None                                     |
	| UCHIJAA | pyrotech  | 1.12.2-1.4.20 | pyrotech-1.12.2-1.4.20.jar    | None                                     |

	Loaded coremods (and transformers): 
	GL info: ~~ERROR~~ RuntimeException: No OpenGL context found in the current thread.
	Profiler Position: N/A (disabled)
	Player Count: 0 / 8; []
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'fml,forge'

I've updated Forge and tried numerous things but I still keep getting the crash every time I create or load a game world.

**Comment by codetaylor** [comment]
When you submit an issue, please read and follow the provided issue template instead of ignoring and deleting it -- it is provided for a reason.

**Comment by codetaylor** [comment]
Using any version of Forge 1.12.2 released after November 23, 2018 will solve this issue.
