### ISSUE TITLE
Allow core.compat.Wood-Custom to accept domain:path:meta

### ISSUE THREAD

**Issue by Kurtchekov** [codetaylor/pyrotech#67]
#### Issue Description

I need to map debarked logs from Leather Works mod to vanilla planks, which seems impossible to achieve with the new system (though my CraftTweaker script still works fine). Maybe a separate entry just for domain:path:meta format?

By the way, funny thing, if I try to use domain:path:meta:

```
java.lang.ArrayIndexOutOfBoundsException: 1
	at com.codetaylor.mc.athenaeum.parser.recipe.item.RecipeItemParser.parse(RecipeItemParser.java:71)
	at com.codetaylor.mc.pyrotech.modules.tech.basic.init.recipe.ChoppingBlockRecipesAdd.getItemStack(ChoppingBlockRecipesAdd.java:91)
	at com.codetaylor.mc.pyrotech.modules.tech.basic.init.recipe.ChoppingBlockRecipesAdd.createRecipe(ChoppingBlockRecipesAdd.java:55)
	at com.codetaylor.mc.pyrotech.modules.tech.basic.init.recipe.ChoppingBlockRecipesAdd.applyCompatRecipes(ChoppingBlockRecipesAdd.java:44)
	at com.codetaylor.mc.pyrotech.modules.tech.basic.ModuleTechBasic.onRegisterRecipesEvent(ModuleTechBasic.java:116)
	at com.codetaylor.mc.athenaeum.module.ModuleEventRouter.lambda$onRegisterRecipesEvent$32(ModuleEventRouter.java:176)
	at com.codetaylor.mc.athenaeum.module.ModuleEventRouter.fireEvent(ModuleEventRouter.java:202)
	at com.codetaylor.mc.athenaeum.module.ModuleEventRouter.onRegisterRecipesEvent(ModuleEventRouter.java:176)
```

The exception is throwing an exception! It's glorious! xD

#### Affected Versions

* Minecraft: 1.12
* Forge: 14.23.5.2838
* CraftTweaker: 4.1.19
* Dropt: 1.15.0
* Pyrotech: 1.1.0
* Athenaeum: 1.17.1

**Comment by codetaylor** [comment]
In the next version, the generated file for wood compat will be in a new format:

```js
{
  "__comments": [
    "WARNING: All changes should be made to the file with the name Custom",
    "in the title. Changes made to the Generated file will be overwritten.",
    "",
    "This file defines input and output pairs for auto-generating recipes",
    "for the Chopping Block.",
    "",
    "Entries are in the format (input): (output)",
    "Entry item strings are in the format: (domain):(path):(meta)"
  ],
  "entries": {
    "minecraft:log2:0": "minecraft:planks:4",
    "minecraft:log2:1": "minecraft:planks:5",
    "minecraft:log:0": "minecraft:planks:0",
    "minecraft:log:1": "minecraft:planks:1",
    "minecraft:log:2": "minecraft:planks:2",
    "minecraft:log:3": "minecraft:planks:3",
    "minecraft:planks:0": "minecraft:wooden_slab:0",
    "minecraft:planks:1": "minecraft:wooden_slab:1",
    "minecraft:planks:2": "minecraft:wooden_slab:2",
    "minecraft:planks:3": "minecraft:wooden_slab:3",
    "minecraft:planks:4": "minecraft:wooden_slab:4",
    "minecraft:planks:5": "minecraft:wooden_slab:5"
  }
}
```

**Comment by Kurtchekov** [comment]
Version 1.1.1 now crashes the game once the core.compat.Wood-Custom gets generated. I have tried deleting custom and generated but it still crashes. Removing the new Leather Works oredict entries from the custom one fixes the problem.

```
[01:28:38] [Client thread/WARN] [FML]: Registry ChoppingBlockRecipe: Override did not have an associated owner object. Name: pyrotech:minecraft_planks_4 Value: com.codetaylor.mc.pyrotech.modules.tech.basic.recipe.ChoppingBlockRecipe@4d5d640b
[01:28:38] [Client thread/WARN] [FML]: Registry ChoppingBlockRecipe: Override did not have an associated owner object. Name: pyrotech:minecraft_planks_2 Value: com.codetaylor.mc.pyrotech.modules.tech.basic.recipe.ChoppingBlockRecipe@514a878c
[01:28:38] [Client thread/WARN] [FML]: Registry ChoppingBlockRecipe: Override did not have an associated owner object. Name: pyrotech:minecraft_planks_5 Value: com.codetaylor.mc.pyrotech.modules.tech.basic.recipe.ChoppingBlockRecipe@de8389b
[01:28:38] [Client thread/WARN] [FML]: Registry ChoppingBlockRecipe: Override did not have an associated owner object. Name: pyrotech:minecraft_planks_3 Value: com.codetaylor.mc.pyrotech.modules.tech.basic.recipe.ChoppingBlockRecipe@3514077b
[01:28:38] [Client thread/WARN] [FML]: Registry ChoppingBlockRecipe: Override did not have an associated owner object. Name: pyrotech:minecraft_planks_0 Value: com.codetaylor.mc.pyrotech.modules.tech.basic.recipe.ChoppingBlockRecipe@4911a47a
[01:28:38] [Client thread/WARN] [FML]: Registry ChoppingBlockRecipe: Override did not have an associated owner object. Name: pyrotech:minecraft_planks_1 Value: com.codetaylor.mc.pyrotech.modules.tech.basic.recipe.ChoppingBlockRecipe@5040c22f
[01:28:38] [Client thread/INFO] [STDOUT]: [net.minecraft.init.Bootstrap:func_179870_a:553]:

java.lang.RuntimeException: One of more entry values did not copy to the correct id. Check log for details!
```

**Comment by Kurtchekov** [comment]
Tested version 1.1.3 here, problem fixed! Nice work! ^^
