### ISSUE TITLE
Getting an error with Thermal Expansion.

### ISSUE THREAD

**Issue by BillboardEric** [codetaylor/pyrotech#8]
Not sure how relevant it is, but I use VanillaFix and received this error on loading of the world. Not sure if it actually has any noticeable effects between Pyrotech and TE but thought I would post the log in case.

Should be able to reproduce with an instance of Pyrotech, TE, and VanillaFix

Log Here:
https://paste.dimdev.org/quvimuraro.mccrash

**Comment by codetaylor** [comment]
I don't know why the game is crashing, but I'm fairly certain it isn't Pyrotech.

The stacktrace provided doesn't show Pyrotech at all in the code path.

To be thorough, however, I did attempt to reproduce it and was unable to using the following instance:

```
| State  | ID                | Version         | Source                                          | Signature                                |
|:------ |:----------------- |:--------------- |:----------------------------------------------- |:---------------------------------------- |
| LCHIJA | minecraft         | 1.12.2          | minecraft.jar                                   | None                                     |
| LCHIJA | mcp               | 9.42            | minecraft.jar                                   | None                                     |
| LCHIJA | FML               | 8.0.99.99       | forge-1.12.2-14.23.5.2838.jar                   | e3c3d50c7c986df74c645c0ac54639741c90a557 |
| LCHIJA | forge             | 14.23.5.2838    | forge-1.12.2-14.23.5.2838.jar                   | e3c3d50c7c986df74c645c0ac54639741c90a557 |
| LCHIJA | athenaeum         | 1.12.2-1.17.0   | athenaeum-1.12.2-1.17.0.jar                     | None                                     |
| LCHIJA | codechickenlib    | 3.2.2.353       | CodeChickenLib-1.12.2-3.2.2.353-universal.jar   | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
| LCHIJA | redstoneflux      | 2.1.0           | RedstoneFlux-1.12-2.1.0.6-universal.jar         | 8a6abf2cb9e141b866580d369ba6548732eff25f |
| LCHIJA | cofhcore          | 4.6.3           | CoFHCore-1.12.2-4.6.3.27-universal.jar          | None                                     |
| LCHIJA | cofhworld         | 1.3.1           | CoFHWorld-1.12.2-1.3.1.7-universal.jar          | 8a6abf2cb9e141b866580d369ba6548732eff25f |
| LCHIJA | dropt             | 1.12.2-1.14.0   | dropt-1.12.2-1.14.0.jar                         | None                                     |
| LCHIJA | pyrotech          | 1.0.0           | pyrotech-1.0.0.jar                              | None                                     |
| LCHIJA | thermalfoundation | 2.6.3           | ThermalFoundation-1.12.2-2.6.3.27-universal.jar | 8a6abf2cb9e141b866580d369ba6548732eff25f |
| LCHIJA | thermalexpansion  | 5.5.4           | ThermalExpansion-1.12.2-5.5.4.43-universal.jar  | 8a6abf2cb9e141b866580d369ba6548732eff25f |
| LCHIJA | vanillafix        | 1.0.10-SNAPSHOT | VanillaFix-1.0.10-99.jar                        | None                                     |
```

**Comment by codetaylor** [comment]
Yeah, this looks like a TE issue.

**Comment by BillboardEric** [comment]
Got it. 
Just as a BTW, I reproduced by using all those mods you used plus JEI.

**Comment by codetaylor** [comment]
I added JEI and tried again, but still can't reproduce. Everything seems fine.

JEI: jei_1.12.2-4.15.0.280

Again, I'm pretty sure this is a Thermal Expansion (TE) issue. The NPE in the stacktrace is indicating a null value [on this line](https://github.com/CoFH/ThermalExpansion/blob/1.12/src/main/java/cofh/thermalexpansion/plugins/jei/machine/enchanter/EnchanterRecipeCategory.java#L78) in TE's code, probably `JEIPluginTE.jeiRuntime`, but I don't know for sure, because it's not my stuff and I don't know what would cause that to be null.

I recommend giving them the crash report and see what they make of it.

**Comment by codetaylor** [comment]
Ok, nevermind, I was able to reproduce some kind of conflict with Thermal Expansion:

```
[21:25:33] [Client thread/ERROR]: Failed to register mod plugin: class cofh.thermalexpansion.plugins.jei.JEIPluginTE
java.lang.NullPointerException: null
	at com.codetaylor.mc.pyrotech.proxy.ClientSidedProxy.playSound(ClientSidedProxy.java:27) ~[ClientSidedProxy.class:?]
	at com.codetaylor.mc.pyrotech.modules.bucket.item.ItemBucketBase$BucketWrapper.setFluid(ItemBucketBase.java:786) ~[ItemBucketBase$BucketWrapper.class:?]
	at net.minecraftforge.fluids.capability.wrappers.FluidBucketWrapper.drain(FluidBucketWrapper.java:173) ~[FluidBucketWrapper.class:?]
	at cofh.thermalexpansion.plugins.jei.machine.transposer.TransposerRecipeWrapperContainer.<init>(TransposerRecipeWrapperContainer.java:47) ~[TransposerRecipeWrapperContainer.class:?]
	at cofh.thermalexpansion.plugins.jei.machine.transposer.TransposerRecipeCategoryFill.getRecipes(TransposerRecipeCategoryFill.java:90) ~[TransposerRecipeCategoryFill.class:?]
	at cofh.thermalexpansion.plugins.jei.machine.transposer.TransposerRecipeCategoryFill.initialize(TransposerRecipeCategoryFill.java:44) ~[TransposerRecipeCategoryFill.class:?]
	at cofh.thermalexpansion.plugins.jei.machine.transposer.TransposerRecipeCategory.initialize(TransposerRecipeCategory.java:42) ~[TransposerRecipeCategory.class:?]
	at cofh.thermalexpansion.plugins.jei.JEIPluginTE.register(JEIPluginTE.java:112) ~[JEIPluginTE.class:?]
	at mezz.jei.startup.JeiStarter.registerPlugins(JeiStarter.java:202) [JeiStarter.class:?]
	at mezz.jei.startup.JeiStarter.start(JeiStarter.java:73) [JeiStarter.class:?]
	at mezz.jei.startup.ProxyCommonClient.loadComplete(ProxyCommonClient.java:136) [ProxyCommonClient.class:?]
	at mezz.jei.JustEnoughItems.loadComplete(JustEnoughItems.java:55) [JustEnoughItems.class:?]
```

And this clearly indicates there's a problem on my end. I'll dig into it.

**Comment by codetaylor** [comment]
Ok, it looks like TE is checking out Pyrotech's buckets and the bucket tries to play a sound with a null player as a result.

A null check should fix it.
